/*
 * Copyright (c) 2020.
 * All rights reserved to Ludovico Latini. Program written entirely by Ludovico Latini for the PA1920 project, it is strictly forbidden to use this program for profit, but it can be redistributed for free in an updated version. If redistributed, the program must have the same copyright and Ludovico Latini must be mentioned.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget106239.view.consoleView;

/**
 * Permette di creare un view che, sia GUI che console o di altro tipo dovrà implementare la visione dei menù
 */
public interface View {

     void menuView();
     void categoryView();
     void reportMenu();
     void goalView();
}
