/*
 * Copyright (c) 2020.
 * All rights reserved to Ludovico Latini. Program written entirely by Ludovico Latini for the PA1920 project, it is strictly forbidden to use this program for profit, but it can be redistributed for free in an updated version. If redistributed, the program must have the same copyright and Ludovico Latini must be mentioned.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget106239.model;

import java.io.IOException;

/**
 * Interfaccia implementata da Goal
 */
public interface GoalInterface {
    void setAim(double aim) throws SignException;
    double getBudget(String name) throws IOException, SignException;
    void setBudget(double budget) throws SignException;
    void createNewGoal(String nameOfGoal,double aim) throws IOException, SignException;
    void addMoney(String nameOfGoal, double budgetToAdd) throws SignException, IOException, BankException;
    void subMoney(String nameOfGoal, double budgetToSub) throws SignException, IOException, BankException;
    String control(String name) throws IOException, SignException;
    void deleteGoal(String goal) throws IOException, DelException, SignException;
}
