/*
 * Copyright (c) 2020.
 * All rights reserved to Ludovico Latini. Program written entirely by Ludovico Latini for the PA1920 project, it is strictly forbidden to use this program for profit, but it can be redistributed for free in an updated version. If redistributed, the program must have the same copyright and Ludovico Latini must be mentioned.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget106239.model;

import java.io.IOException;

/**
 * Quest'interfaccia permette di creare una cassa e chiede a chi la estende di implementare i metodi base per
 * l'aggiunta e la sottrazione dei soldi con il relativo testo da associare
 */
public interface SavingsInterface {
   double getBank() throws IOException, SignException;
   void addMoney(double money) throws IOException, SignException;
   void subMoney(double money) throws SignException, IOException, BankException;
   void setBank(double bank) throws SignException;
   void addMoney(double money, String text) throws IOException, SignException;
   void subMoney(double money, String text) throws IOException, SignException;
   String getText();
   void setText(String text);
}
