/*
 * Copyright (c) 2020.
 * All rights reserved to Ludovico Latini. Program written entirely by Ludovico Latini for the PA1920 project, it is strictly forbidden to use this program for profit, but it can be redistributed for free in an updated version. If redistributed, the program must have the same copyright and Ludovico Latini must be mentioned.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget106239.controller;

import it.unicam.cs.pa.jbudget106239.model.BankException;
import it.unicam.cs.pa.jbudget106239.model.DelException;
import it.unicam.cs.pa.jbudget106239.model.SignException;

import java.io.IOException;
import java.util.LinkedList;

/**
 * Permette di creare un menu, il menu che verrà creato dovrà implementare questi metodi
 */
public interface MenuInterface {
    LinkedList<String> getAccount();
    void selAccount(String x);
    void createAccount(String x, double y) throws IOException, SignException;
    void delAccount(String x) throws IOException, DelException;
    void deleteGoal(String str0) throws SignException, DelException, IOException;
    String compare(String str) throws IOException, SignException;
    void createGoal(String name, double aim) throws IOException, SignException;
    void addMoneyToGoal(String name,double money) throws IOException, SignException, BankException;
    void subMoneyToGoal(String name, double money) throws IOException, SignException, BankException;
    void addMoney(double MoneyToAdd,String MotivationForReport) throws IOException, SignException;
    void decrementMoney(double MoneyToRemove, String MotivationForReport) throws IOException, SignException;
    void AddCategory (String x) throws IOException;
    LinkedList<String> printCategory(String x) throws IOException;
    void moneyOnCategory(double mon, String mot, String nome) throws IOException, SignException;
    void deleteCategory (String str0) throws DelException, IOException;
    LinkedList<String> printReport() throws IOException;
    LinkedList<String> printPositiveReport() throws IOException;
    LinkedList<String> printNegativeReport() throws IOException;
}
